config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :session, only: [:create, :destroy]

  resources :puzzles, only: [:index, :show, :new, :create, :edit] do
    collection do
      get :random
    end
  end

  resources :users, only: [] do
    resources :puzzles, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :words, only: [:index] do
        collection do
          get :analyze
        end
      end

      resources :puzzles, only: [:show, :update] do
        member do
          patch :publish
          put :publish
        end
      end

      resources :users, only: [] do
        resources :solutions, only: [:update]
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def sign_in
  end
end

app/views/static_pages/index.html.erb
<div class="main-image">
  <%= image_tag "grid.png" %>
  <div class="try-now">
    <%= link_to "Play Now", random_puzzles_path %>
  </div>
</div>

<div class="lower columns">
  <div class="small-12 small-centered columns">
    <h3>Welcome to Cross Reaction!</h3>
    <p>
      Cross Reaction is a modern browser-based interface for solving and creating crossword puzzles. The puzzles found here are community contributed. Tools are available to help first-time constructors and pros alike build puzzles to share.
      You'll get the most out of this site by signing in so that we can save your solutions and drafts.
    </p>
    <br>
    <p>
      This app was built by Andrew Rogers while at Launch Academy.
    </p>
    <a href="https://github.com/andrewprogers/crossword-react-on-rails">
      <%= image_tag 'github_mark.png' %>
    </a>
    <a href="https://www.linkedin.com/in/andrew-paul-rogers/">
      <%= image_tag 'linked_in_mark.png', width: "32px" %>
    </a>

  </div>
</div>