config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :session, only: [:create, :destroy]

  resources :puzzles, only: [:index, :show, :new, :create, :edit] do
    collection do
      get :random
    end
  end

  resources :users, only: [] do
    resources :puzzles, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :words, only: [:index] do
        collection do
          get :analyze
        end
      end

      resources :puzzles, only: [:show, :update] do
        member do
          patch :publish
          put :publish
        end
      end

      resources :users, only: [] do
        resources :solutions, only: [:update]
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cross Reaction</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:300" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="top">
      <div class="title"><%= link_to "Cross Reaction", root_path, id: "title" %></div>
      <div class="top-left">
        <%= link_to "Play", puzzles_path, class: "nav-link" %>
        <% if current_user %>
          <%= link_to "Create", new_puzzle_path, class: "nav-link" %>
          <%= link_to "My Puzzles", user_puzzles_path(current_user), class: "nav-link" %>
        <% end %>
      </div>
      <div class="top-right">
        <% if current_user %>
          <%= link_to "Sign Out", '/signout' , class: "nav-link"%>
          <span id="user-name"><%= current_user.name %></span>
          <%= image_tag current_user.avatar_url, class: "avatar" unless current_user.avatar_url.nil? %>
        <% else %>
          <%= link_to "Sign in with Google", '/auth/google_oauth2', id: "sign_in", class: "nav-link sign-in" %>
        <% end %>
      </div>
    </div>



    <div class="flash-container">
      <% flash.each do |key, msg| %>
        <div class="flash-msg flash-<%= key %>">
          <span><%= msg %></span>
        </div>
      <% end %>

      <!-- <div class="flash-msg">
        <span>This is a test alert</span>
      </div>
      <div class="flash-msg flash-error">
        <span>This is a test Error</span>
      </div>
      <div class="flash-msg flash-notice">
        <span>This is a test Notice</span>
      </div> -->
    </div>

    <div class="">
      <%= yield %>
    </div>

    <script type="text/javascript">
      $(document).foundation()
    </script>
  </body>
</html>